### PR TITLE
Update README.md with info for running using emulator.

### PR DESCRIPTION
**Pull request by winksaville**

### CODE REVIEW

**Comment by winksaville** [comment]
@stuartmscott, updated the README.md, but the real reason that you check things are "working" well enough to proceed. Right now most of the submodules are still pointing at my repo's. But I not only created PerspectiveSuite and JavaCommon I've switched AletheiaWareLLC/AletheiaWareCommonJava from using my fork to the official version.

The change you made to AletheiaWareLLC/AletheiaWareCommonJava/build.sh worked perfectly without changes so I just removed the submodule that was pointing at winksaville and pointed it to AletheiaWareLLC. So good job.

So please, check what I've done so far. You should be able to clone PerspecitveSutie using the README.md and buld and test. Let me know if there are any changes you'd like before we do the other submodules that are stll pointing at winksaville.

To change a submodule to point to a different repo you first remove the existing repo:
```
git submodule deinit <path_to_submodule>
git rm <path_to_submodule>
git commit -m "Removed submodule "
rm -rf .git/modules/<path_to_submodule>
```
And then add a new submodule:
```
git add submodule git@github.com:AletheiaWareLLC/<submodule>
git commit -m "Add submodule"
```
Feel free to give it a try!

**Comment by stuartmscott** [comment]
Clone
```
$ git clone --recursive git@github.com:AletheiaWareLLC/PerspectiveSuite.git
```
Build
```
$ cd PerspectiveSuite/
$ ./build.sh 
```
Install
```
$ adb install ./PerspectiveAndroid/app/build/outputs/apk/debug/app-debug.apk
Performing Streamed Install
adb: failed to install ./PerspectiveAndroid/app/build/outputs/apk/debug/app-debug.apk: Failure [INSTALL_FAILED_VERSION_DOWNGRADE]
```
This is failing because the PerspectiveAndroid submodule still points to your fork.
After changing the submodules to point to AW's forks it builds, installs, and runs!
```
$ git submodule deinit JoyJava
$ git submodule deinit PerspectiveJava
$ git submodule deinit AletheiaWareCommonAndroid
$ git submodule deinit JoyAndroid
$ git submodule deinit PerspectiveAndroid
$ rm -r JoyJava
$ rm -r PerspectiveJava
$ rm -r AletheiaWareCommonAndroid
$ rm -r JoyAndroid
$ rm -r PerspectiveAndroid
$ rm -rf .git/module/JoyJava
$ rm -rf .git/module/PerspectiveJava
$ rm -rf .git/module/AletheiaWareCommonAndroid
$ rm -rf .git/module/JoyAndroid
$ rm -rf .git/module/PerspectiveAndroid
$ git submodule add -f git@github.com:AletheiaWareLLC/JoyJava
$ git submodule add -f git@github.com:AletheiaWareLLC/PerspectiveJava
$ git submodule add -f git@github.com:AletheiaWareLLC/AletheiaWareCommonAndroid
$ git submodule add -f git@github.com:AletheiaWareLLC/JoyAndroid
$ git submodule add -f git@github.com:AletheiaWareLLC/PerspectiveAndroid
$ ./build.sh
$ adb install ./PerspectiveAndroid/app/build/outputs/apk/debug/app-debug.apk
Performing Streamed Install
Success
```

**Comment by winksaville** [comment]
I think I understand why "INSTAL_FAILED_VERSION_DOWNGRADE", you had updated PerspectiveAndroid version in app/build.gradle and installed the new version. Then, when you tried to install my older version it failed. I've now updated the version in my repo, adding Update-app-versoin branch and PerspectiveSuite/PerspecitiveAndroid now points to the new branch.

It should now work for you without any changes if you use this new version. Please give it a try by cloning PerspectiveSutie to a new directory. Or If you reset your copy of PerspectiveSuite back to thos branch's parent then pull in the new commit, that should work too.

**Comment by winksaville** [comment]
Oh, what protocol do you want to follow for merging reviewed changes:
1) The "reviewer" justs merge if they approve and have commit rights.

2) If the author of the PR has commit rights then the reviewer can give a
LGTM label/comment or some such and the author can merge.

What convention would you like to use either of the above or maybe something else?

Of course, usually there would be tests and no merges would happen unless CI tests passed.

**Comment by stuartmscott** [comment]
Sorry, my last message wasn't clear - the INSTALL_FAILED_VERSION_DOWNGRADE error was good - it showed that the install fails when the submodules are pointing to your forks. I then verified that it succeeds after updating the submodules.

This PR with only the README.md change (ie. without https://github.com/AletheiaWareLLC/PerspectiveSuite/pull/1/commits/c97450c396479d6878ee2ea1ddbfa519c51b0c84) can be merged.

Then I'll merge the .gitmodule update pointing the submodules to the AW repos.

Next, the Go stuff can be removed from PerspectiveSuite/build.sh - it need only contain Java/Android stuff and need not generate the Go protos.

That's a good question. I think the coder has the most context about the change such as related changes and schedule, therefore they should pull the trigger and merge it after the reviewer(s)  adds the "LGTM" label.

**Comment by winksaville** [comment]
> Sorry, my last message wasn't clear - the INSTALL_FAILED_VERSION_DOWNGRADE error was good - it showed that the install fails when the submodules are pointing to your forks. I then verified that it succeeds after updating the submodules.

Hmm, I probably not understaning, but I don't believe it failed just because it was pointing to my repo, it failed because my repo was out of date. It doesn't matter where the repo is located as long as it a "public" it is a public URL then XxxxSuite can point to and build it.

For example winksaville/PerspectiveSuite has some submodules from AletheiaWareLLC and some from winksaville, see .gitmodules from winksaville/PerspecitiveSuite. We see that `Joy` and `Perspecitve` are from `AletheiaWareLLC` and the rest are from `winksaville`:
```
$ cat .gitmodules
[submodule "Joy"]
	path = Joy
	url = git@github.com:AletheiaWareLLC/Joy.git
[submodule "Perspective"]
	path = Perspective
	url = git@github.com:AletheiaWareLLC/Perspective.git
[submodule "JavaCommon"]
	path = JavaCommon
	url = git@github.com:winksaville/JavaCommon.git
[submodule "AletheiaWareCommonJava"]
	path = AletheiaWareCommonJava
	url = git@github.com:winksaville/AletheiaWareCommonJava.git
[submodule "JoyJava"]
	path = JoyJava
	url = git@github.com:winksaville/JoyJava.git
[submodule "PerspectiveJava"]
	path = PerspectiveJava
	url = git@github.com:winksaville/PerspectiveJava.git
[submodule "AletheiaWareCommonAndroid"]
	path = AletheiaWareCommonAndroid
	url = git@github.com:winksaville/AletheiaWareCommonAndroid.git
[submodule "JoyAndroid"]
	path = JoyAndroid
	url = git@github.com:winksaville/JoyAndroid.git
[submodule "PerspectiveAndroid"]
	path = PerspectiveAndroid
	url = git@github.com:winksaville/PerspectiveAndroid.git
```

> This PR with only the README.md change (ie. without [c97450c](https://github.com/AletheiaWareLLC/PerspectiveSuite/commit/c97450c396479d6878ee2ea1ddbfa519c51b0c84)) can be merged.

> Then I'll merge the .gitmodule update pointing the submodules to the AW repos.

Just changing .gitmodule won't work, those series of `git submodule add ...` you did are also
necessary and then you need to commit the the changes from .gitmodules and the submodule special node's.

Also, PerspectiveAndroid and JoyAndroid have additional changes to .gitignore and gradle changes.

> 
> Next, the Go stuff can be removed from PerspectiveSuite/build.sh - it need only contain Java/Android stuff and need not generate the Go protos.

I'm not sure how to do that, as I understand it, Joy and Perspective build both the go and java versions of the protobuf, which means we need that. Do you mean you want to create a build_go.sh and an build_java.sh in Joy and Perspective (I'm probably just really confused).

> 
> That's a good question. I think the coder has the most context about the change such as related changes and schedule, therefore they should pull the trigger and merge it after the reviewer(s) adds the "LGTM" label.

OK.

**Comment by stuartmscott** [comment]
> it failed because my repo was out of date.

Yes - my device was running v0.6 so it failed to install the APK built with your forks containing v0.5. After changing the submodules to point to AW's repos (containing v0.6) the APK built, installed, and run without issue. So we are good, you can merge this PR with the README.md change and without the app/build.gradle change (the version bump is not needed because master HEAD is already v0.6)

> Just changing .gitmodule won't work, those series of git submodule add ... you did are also
necessary and then you need to commit the the changes from .gitmodules and the submodule special node's.

https://github.com/AletheiaWareLLC/PerspectiveSuite/pull/2 contains both the changes to .gitmodule and the submodule nodes.

> Also, PerspectiveAndroid and JoyAndroid have additional changes to .gitignore and gradle changes.

Master HEAD has the changes to add the gradle wrapper, let me know if I've missed anything else.

> I'm not sure how to do that, as I understand it, Joy and Perspective build both the go and java versions of the protobuf, which means we need that. Do you mean you want to create a build_go.sh and an build_java.sh in Joy and Perspective (I'm probably just really confused).

No worries, I meant that PerspectiveSuite can focus on the Java/Android side and doesn't need to build the go versions of the protobuf. I've made this change as part of https://github.com/AletheiaWareLLC/PerspectiveSuite/pull/3

**Comment by winksaville** [comment]
OK, I'll merge the just the README.md change

**Pull request merged**
