### PR TITLE
Latest PerspectiveAndroid.

### PR DESCRIPTION
**Pull request by winksaville**
An update to its README.md.

### CODE REVIEW

**Comment by winksaville** [comment]
I rebased this and forced push, it should just be a single commit despite saying its 2 commits. I think you should approve and we'll see if it works. If you'd rather not I can close and redo it without any trouble.

**Comment by stuartmscott** [comment]
Woah there's something not right here: it includes both the Gradle change and the update to the PerspectiveAndroid submodule.
It is "winksaville wants to merge 2 commits into Use-gradle-to-execute-build.sh from Latest-PerspectiveAndroid", shouldn't it be merging into master?

**Comment by winksaville** [comment]
Yeah it looks a little wonky, I rebased it but GitHub doesn't seem to be
displaying correctly. If u look at the change and it's parent it looks OK
to me. We can do a forced update of master if all else fails and we learn
something if we try this.

But if you'd prefer I'll create a separate change off master.

**Review by stuartmscott — APPROVED** [review]
Changed the base branch and now the only change is the PerspectiveAndroid submodule update

**Pull request merged**
