### PR TITLE
Modify Scripts

### PR DESCRIPTION
**Pull request by stuartmscott**
- Adds hash-bang bash
- Adds copyright
- Uses 'e' flag to exit on error
- Uses 'x' flag to echo command being executed
- Removes Go stuff

### CODE REVIEW

**Review by winksaville — APPROVED** [review]
I added the echo statements because it was hard to see which build failed, this may not be needed since you've added "set -e and -x" but maybe adding some blank lines or "-----" to separate each of these might be helpful.

**Comment by stuartmscott** [comment]
Using 'set -x' is nice because it shows exactly what is being executed and, unlike echo statements, is kept up-to-date automatically. Having said that, the console does get filled with blocks of text and it can be difficult to see where one command ends and another started.

The echo statements you added had "***" which separated each command, making it easier to spot the boundaries. I could re-add them, but the command would also get printed, ie:
```
echo "***"
foobar
```
Will print;
```
+ echo "***"
***
+ foobar
```
Another option is to disable '-x' for just the echo;
```
(set +x && echo "***")
foobar
```
But this has a similar disadvantage;
```
+ set +x
***
+ foobar
```
Thoughts?

**Comment by winksaville** [comment]
What about commenting out the `set -x` the adding the echo's back in, that keeps the build output "cleaner" and easier to read in the typical case, and if an error occurs where more information is desired the programer can uncomment the `set -x`.

Actually, using build.sh isn't a great option, IMHO, a "real" make system should be used in the future.

A related issue with the current build system is that every project is unconditionally "built" every time. What I ended up doing for llvm in the pony llvm [Makefile](https://github.com/ponylang/ponyc/blob/master/lib/llvm/Makefile) was creating "LLVM_TGT_DIR" variable and using it in [llvm-base.rules](https://github.com/ponylang/ponyc/blob/master/lib/llvm/llvm-base.rules) to quickly skip steps that had completed. It's not perfect but under normal circumstances llvm only needs to be created once and wasting time runing "make" with nothing to do was aggravting as doing nothing on llvm still takes time and casued too much output.

`PerspectiveSuite` has a similar issue as typically only a small subset of the submodules are being worked on at any one time, i.e. I'm guessing it's mostly `PerspectiveAndroid`.

For the short term this doesn't need to be addressed, but maybe in the future it does.

**Comment by stuartmscott** [comment]
Ack. I'll comment out "set -x" and re-add the echos.

I agree that longer term a build system should be used and have created https://github.com/AletheiaWareLLC/PerspectiveSuite/issues/4 to track.

**Pull request merged**
